### ISSUE TITLE
Documentation: Add Issue Tracker / Dashboard

### ISSUE THREAD

**Issue by cwatsonc** [freeboardgames/FreeBoardGames.org#1012]
**Problem Statement**
The organic project structure isn't going to scale much longer and searching for and collating documentation/artifacts should start to take form -- devs have called for some structure to the project level artifacts starting with dashboard.

**Proposed Solution**
The project needs an anchor for roadmap related items -- devs have identified the dashboard metaphor to be added to the landing area of freeboardgames.org. It will include project metrics and root level links to various artifacts.

**Discussion Points/Alternatives**
[Test Coverage Reports Issue #561](https://github.com/freeboardgames/FreeBoardGames.org/issues/561)
[Roadmap Discussions - Lobby #941 ](https://github.com/freeboardgames/FreeBoardGames.org/issues/941)
[Labels Proposal Article](https://seantrane.com/posts/logical-colorful-github-labels-18230/)
[Tabler Dashboard Project](https://github.com/tabler/tabler)

**Additional Context**
Sandbox Status To Close By Jan 1, 2022
TBD

**Comment by cwatsonc** [comment]
@richardaum let's start by collecting ideas and reference links in the comments.  We can add them to the main body as required.  How do I make this editable by another author?

**Comment by richardaum** [comment]
> How do I make this editable by another author?

It is already editable by contributors.

**Comment by richardaum** [comment]
> Any thoughts about having a feature backlog (maybe as a GH issue)? IMO we need to understand how to evolve our app (not only infra but also features).

By saying that, I mean to know to where this app is moving forward, by letting clear which efforts are prioritized, their status and so on.

**Suggestion:** 
This [article](https://seantrane.com/posts/logical-colorful-github-labels-18230/) looks reasonable for what we need. It brings a few type of labels we could enforce the use.

![image](https://user-images.githubusercontent.com/2018161/142699647-c7a55bba-6432-4b56-8304-4d90457b3693.png)

**Comment by cwatsonc** [comment]
Good article I have lifted it to the main issue as a proposal -- maybe we'll get competing ones, but for now it's likely just you and me until we draw some interest.  Are you able to edit the main issue?

**Comment by cwatsonc** [comment]
So do I read into your comments that the bulk of this lift is through oob GitHub issue facilities?  Are there alternatives to issues app in the header?  I've done no customization of GitHub on my own repos -- maybe we can get some guidance from the others who have more experience with managing the customizations -- maybe we can look to bgio's use patterns to describe similar practices?  @vdfdev @jasonharrison

**Comment by richardaum** [comment]
> maybe we can look to bgio's use patterns to describe similar

That is easy to do.

![image](https://user-images.githubusercontent.com/2018161/142742242-f1fdfbfb-6c07-4cfa-a281-c31eabc4f887.png)

It looks like they use the default labels. But I'm not sure if they are a good reference to that specific way of organizing issues. 

We could take as reference the [Typescript repo](https://github.com/microsoft/TypeScript/issues), which have a way more labels (also more developer interaction).

![image](https://user-images.githubusercontent.com/2018161/142742304-519c5cf8-0456-4b03-889d-51b951f47be1.png)

But again, it is not specifically about adding labels or not, my main concern is about being more active here on Github issues, and using labels seems to be a way IMO.

**Comment by cwatsonc** [comment]
Take a look at how the storybook team organizes their effort --  I was in a "water-cooler" chat they advertised on their Discord -- twice weekly they triage their backlog but they have a planned release every 30 days or so -- it was a really cool experience to sit on in -- I wouldn't mind approaching them for some ideas on how they organize -- they are not a Free product but are developing Chromatic -- a software framework that eases development with SB @richardaum I agree better focus on roadmap and goals would pay off pretty well -- it's just hard to get the many heads of this loose knit community to act in concert -- that's usually a very strong focus by one or two "keys" in my experience. /$0.02

**Comment by cwatsonc** [comment]
From a Sunday (11/28)  conversation with @richardaum the following summary:

For FGB, we need to: 

- Grow our number of players

While: 

- Get users feedback, to understand if we are going on right direction.
- Minimize costs, to have a sustainable ecossystem.
- Attract high quality contributions, to have good discussions and also good implementations.
- Fast delivery and observability.

**Comment by cwatsonc** [comment]
seems to be off the roadmap for foreseeable future.

**Comment by cwatsonc** [comment]
removing this issue as not in reach for current effort
