### ISSUE TITLE
[Picnic Go] Cupcake cards do not appear

### ISSUE THREAD

**Issue by ProspectPyxis** [freeboardgames/FreeBoardGames.org#1021]
**Describe the bug**
After playing quite a few games with friends, I believe that there's a bug where cupcakes will never appear no matter what. We could be having very bad luck, but it's pretty statistically unlikely.

**To Reproduce**
1. Start multiple games of Picnic Go
2. No players should ever get a cupcake card

**Expected behavior**
Cupcake cards should show up every once in a while for at least a few players.

**Comment by ProspectPyxis** [comment]
Ignore this bug - apparently, I really was just getting worst luck possible...

**Comment by tuxor1337** [comment]
Just for reference, I copy my results from the Discord channel:

A little less than 10 percent of the cards are cupcakes, so it's quite unusual to have no cupcakes at all in any of the three rounds of the game (less than 0.2 % even with only 2 players). However, if you are only talking about the first round, the probability is 11.66 (4.85, 2.47, 1.60) % for 2 (3, 4, 5) players. 

I quickly implemented a test to confirm these numbers: For 2 (3, 4, 5) players, 11,782 (4,782, 2,454, 1,606) out of 100,000 games had no cupcake in the start hands.

This is the code that I used in `game.test.ts`: 

```typescript
import { getCardTypeFromNumber } from './cards';
import { cardEnum } from './types';
it('should often contain cupcakes in start hands', () => {
  for (let numPlayers = 2; numPlayers <= 5; numPlayers++) {
    let n = 0;
    const N = 100000;
    for (let i = 0; i < N; i++) {
      const client = Client({
        game: PicnicGoGame,
        numPlayers,
      });
      const { G, ctx } = client.store.getState();
      let hasDessert = G.hands.some(({ currentOwner, hand }) => {
        return hand.some((e) => getCardTypeFromNumber(e) === cardEnum.cake);
      });
      if (!hasDessert) n += 1;
    }
    console.log(`no dessert in start hands (numPlayers=${numPlayers}): ${n} out of ${N}`);
  }
});
```
Conclusion: There doesn't seem to be a bug related to the distribution of cupcake cards, at least it's not present in the unit test environment for an arbitrary number of players.
