### ISSUE TITLE
[Seabattle] Seabattle message text is sometimes obscured 

### ISSUE THREAD

**Issue by jasonharrison** [freeboardgames/FreeBoardGames.org#215]
![image](https://user-images.githubusercontent.com/304383/57660268-c2d75b00-75b3-11e9-9d30-bb44a2323a1d.png)

**Comment by JosefKuchar** [comment]
Your window height is too small... What can we do about this?

**Comment by flamecoals** [comment]
We could have a CSS that changes the width of the map (which is a square, so the height would be smaller too), but I dont think most usres will have this issue and it will complicate the code/css. I rather invest our time in other stuff for now

**Comment by vdfdev** [comment]
This should be fixed by #923
