### ISSUE TITLE
[Infrastructure] Spectate an ongoing game

### ISSUE THREAD

**Issue by jasonharrison** [freeboardgames/FreeBoardGames.org#272]

**Comment by sahajanand-games** [comment]
I can try my hand at this.

**Comment by gk-patel** [comment]
I can give it a try

**Comment by gk-patel** [comment]
![image](https://user-images.githubusercontent.com/42677721/101920990-c4706700-3bcc-11eb-8d9b-f1d900076ed9.png)
maybe this can be handled better. If the players press the play-again button, technically, the spectators could either be redirected to the main page OR to the new session. 
Whatever is easy .... but the error message should go away.

**Comment by gk-patel** [comment]
![image](https://user-images.githubusercontent.com/42677721/101927176-75c6cb00-3bd4-11eb-8e1a-5e3e4ba5514a.png)
This is what you get when you try to go into full ROOM and the game has not started.

**Comment by flamecoals** [comment]
Hey @gk-patel, do you mind opening two other issues for these things you pointed out? Im going to close this for now because we already support spectating ongoing games

**Comment by gk-patel** [comment]
done!
