### ISSUE TITLE
Display game name in the game bar

### ISSUE THREAD

**Issue by JosefKuchar** [freeboardgames/FreeBoardGames.org#422]
It'd be great to have game name in the game bar as shown in the picture
![image](https://user-images.githubusercontent.com/12010072/72178596-7e6eba00-33e3-11ea-8621-c39cf08c516e.png)

**Comment by jasonharrison** [comment]
I agree.  What should we do if there isn't enough room to fit the game name?

**Comment by JosefKuchar** [comment]
It can be under the fbg title

**Comment by jasonharrison** [comment]
I've thought about this for a bit-- how do we access the game name from within GameDarkSublayout.tsx?

* We don't get the GameDef as a prop (we could change this, but it would involve changing every game's board.tsx).
* We can't use the NextJS router (at least, I don't think we can)
* We _could_ try to parse window.location.pathname, but that feels hacky to me...

https://github.com/freeboardgames/FreeBoardGames.org/blob/master/components/App/Game/GameDarkSublayout.tsx
