### ISSUE TITLE
[Infrastructure] Chat

### ISSUE THREAD

**Issue by JosefKuchar** [freeboardgames/FreeBoardGames.org#428]
It would be nice to have global and game room chat

**Comment by flamecoals** [comment]
I am going to work on game room chat this weekend. I think it can be accomplished with a bgio plugin

**Comment by flamecoals** [comment]
For reference, I did some progress here:
https://github.com/nicolodavis/boardgame.io/pull/629

But bgio doesnt support this out of the box. It seems like it wouldn't be particularly efficient by the discussion we had on that PR either. So I am thinking about creating something in our own server.

**Comment by flamecoals** [comment]
This is in production now!
