### ISSUE TITLE
Reversi game over doesn't show in local mode

### ISSUE THREAD

**Issue by JosefKuchar** [freeboardgames/FreeBoardGames.org#437]
~~Will be fixed in #433~~

**Comment by jasonharrison** [comment]
Issue still exists as of 931b196070df8e43352f532aad99a92728ac08a0

**Comment by jasonharrison** [comment]
![image](https://user-images.githubusercontent.com/304383/78962521-5534f700-7ac2-11ea-9d96-d51e82c30d51.png)

**Comment by jasonharrison** [comment]
It appears the issue is `this.props.playerID` is `null`
