### ISSUE TITLE
Documentation and Readme Update.

### ISSUE THREAD

**Issue by gk-patel** [freeboardgames/FreeBoardGames.org#446]
Hi Guys,

I dont see the link to the blog, which describes how to add a new game.

Moreover, I think it is also important to document our custom Components, such as the once created under created under the games/common or like the once availble from @freeboardgame.org/boardgame.io/ui.

I can do this, but I might need help to get started.

**Comment by jasonharrison** [comment]
Hi,

For the blog, there were some major changes to FBG"s core code / infrastructure a few months ago when we switched to the Next.JS framework.  The blog must have slipped my mind.

About `@freeboardgame.org/boardgame.io/ui`: this is actually straight from an older version of boardgame.io.  The only difference is the fork is an older version of BGIO.  

We are actually in the process of switching to the official boardgame.io package, but there are still issues that we have to resolve.  Check out the PR (which is somewhat outdated): https://github.com/freeboardgames/FreeBoardGames.org/pull/433 

My time has been somewhat constrained lately, but I would like to get working on this PR again.  Help is very much welcome =)

**Comment by gk-patel** [comment]
Hi, 

As I have only recently started contributing to the project, my experience in Infrastructure is very limited. The best I can do is add new games or write proper Doku. :(

**Comment by jasonharrison** [comment]
We switched to the official Boardgame.io package and the blog is back online. 

=)
