### ISSUE TITLE
Game save/load feature

### ISSUE THREAD

**Issue by sparr** [freeboardgames/FreeBoardGames.org#460]
I would like to be able to play half a game then save the state and take a break for a few hours or days, then come back with the same people and finish it.

**Comment by jasonharrison** [comment]
I do think BGIO allows us to save/load game states.  That being said, I'm not sure how useful this functionality would be for our current selection of games.  

Maybe we could add utility methods for saving/loading, and then games that wish to have this functionality could use these methods?

**Comment by flamecoals** [comment]
Duplicate of #461
