### ISSUE TITLE
[Infrastructure] A need for a proper settings interface.

### ISSUE THREAD

**Issue by gk-patel** [freeboardgames/FreeBoardGames.org#473]
Hi Guys, 

In some places, we have felt the need to take inputs from the user before the game starts -- for example, 

![image](https://user-images.githubusercontent.com/42677721/78688591-b52a7280-78f5-11ea-9a02-81ede1e23744.png)

![image](https://user-images.githubusercontent.com/42677721/78688507-a17f0c00-78f5-11ea-950f-41f09eac4bfd.png)

I was thinking that the interface for this should be made better so that we can take even more input before the game starts. Maybe we can have two types of input: Quick Input (which is directly visible) and Detailed Input (which is set of all possible inputs a user can give to customize the game). 

I see the use of this in many cases, a few examples are as follows, 

1. Reversi: the user can increase or decrese the number of boxes, to make the game longer or shorter. 

2. ttt+: the user can change how many the + would come. Currently, the maximum is 3 and minimum is zero; both can be changed. 

3. Hangman: Can set the minimum word lenght, can make Hints mandatory, can control the max char limit of hints, etc. 

All these setting can be made available via small settings button near the play button, which when clicked, opens a settings menu, with all possible settings.

**Comment by sparr** [comment]
This seems like a good place to prompt for things that will go in setupData for game.setup()

**Comment by cwatsonc** [comment]
@sparr @flamecoals is there a framework supported user persistence? Have either of you started on this feature?  A relatively new approach might incorporate local storage on user-agents but a common interface for that makes a lot of sense.  What if the application requires it's own data layer?  It would be good to enumerate the design goals for the UX/UI but also long range plan for how it is incorporated into the framework. 

I don't see an "upvote" feature for this repository, do we track feature "appeal"?

**Comment by vdfdev** [comment]
This was implemented, see our docs: https://www.freeboardgames.org/docs/?path=/story/documentation-game-customization--page
