### ISSUE TITLE
Cornerus - 3 Player issue

### ISSUE THREAD

**Issue by Yannick-S** [freeboardgames/FreeBoardGames.org#484]
We tried playing Cornerus today with three players. The first three moves worked as expected. However after that, it was player four (green's) trun. Player one was able to make the turn for player 4, however afterwards, once it was player 1s turn again, he couldn't make any move, and the game was stuck. We thus aborted :(

**Comment by flamecoals** [comment]
Damn, you are out of luck :/ I will have a look into it tonight

**Comment by flamecoals** [comment]
i could reproduce with al ocal game too. It seems like the game is not allowing to set the second piece, even if it is a valid position. That's what you got too?

I will add a regression test so it doesnt happen again

**Comment by flamecoals** [comment]
okkk, so now with more patience and seeing the rules, I realized that it isnt broken for me. I also tested with 3 players and it worked:

![image](https://user-images.githubusercontent.com/1034631/78965424-e94a9280-7ab1-11ea-862f-c6452674e76a.png)

The gotcha is that in the first turn, you have to place the piece on top of the blue corner, and the turns after that you have to place on the diagonal without touching any side of the previous piece.

I think that the UI doesn't help to explain this to the user, given that we color the first corner with a color that the user needs to overlap. Also, the naming for 3 players is quite confusing, saying "blue turn" and etc. It should be only "YOUR TURN" vs "Waiting for opponent...".

I will see if I can use the chips too with the improvement we talked about on this game too, and move the color corner out of the board, I think it would make it clearer on how to play.

**Comment by flamecoals** [comment]
If this wasnt your case and you found really a bug, feel free to reopen the bug.
