### ISSUE TITLE
Getting Started Blog out of Date and TypeError: this.props.gameArgs is undefined 

### ISSUE THREAD

**Issue by Spooky-0** [freeboardgames/FreeBoardGames.org#491]
Hi,
I am trying to follow the getting started blog post, however have run into a few issues.

In the first commit I made, I have added exactly the code as described in the tutorial.
In the second I fixed a few things. I looked at games like TicTacToe to see how to fix them.

https://github.com/Spooky-0/FreeBoardGames.org/commits/master

Now the program compiles, however once I join a local version of FooBar game I ge tthe following issue: (Shown in the webbrowser.)

```

TypeError: this.props.gameArgs is undefined
render
./src/components/App/Game/GameDarkSublayout.tsx:44

  41 | 
  42 | render() {
  43 |   const isProdChannel = process.env.NODE_ENV === 'production';
> 44 |   const gameName = GAMES_MAP[this.props.gameArgs.gameCode].name;
     | ^  45 |   let fbgTopLeftText;
  46 |   if (isProdChannel) {
  47 |     if (gameName) {

load/<
./src/components/App/Game/Game.tsx:73

  70 | }
  71 | return Promise.all([this.gameDef.config(), aiPromise]).then(
  72 |   (promises: any) => {
> 73 |     this.setState(() => ({
     | ^  74 |       config: promises[0].default as IGameConfig,
  75 |       ai: this.loadAI ? (promises[1].default as IAIConfig) : null,
  76 |       loading: false,


```
This part I sadly don't know how to fix.

I am usually just doing Backend and have some experience in Angular,  but this whole React and Javascript stuff is to foreign for me to be able to figure it out :(.

**Comment by Yannick-S** [comment]
Oh: This part wasn't exaclty copied, but I think the capitaliztion is wrong in the blog

> Then, in the same file, under GAMES_MAP, add foobar: fooBarGameDef, and under GAMES_LIST, add GAMES_MAP.fooBar,.


And in the 'fix for build' commit i accidentaly commit two more changes that have nothign to do with the foobar experiment. 

If I get this to work I can send you a Merge request for the Blog.

**Comment by Yannick-S** [comment]
I got it to work after some searching:

```
export class Board extends React.Component<IBoardProps, {}> {
  render() {
    return (
      <GameLayout>
        <h2>Hello world!</h2>
        <pre>{JSON.stringify(this.props.gameArgs, null, 2)}</pre>
      </GameLayout>
    );
  }
}
```

should be 

```
export class Board extends React.Component<IBoardProps, {}> {
  render() {
    return (
      <GameLayout
!           gameArgs={this.props.gameArgs}>             !
        <h2>Hello world!</h2>
        <pre>{JSON.stringify(this.props.gameArgs, null, 2)}</pre>
      </GameLayout>
    );
  }
}
```

Simple enough. Can you confirm for me that this is indeed the intended fix? I would then go ahead and update the Blog.

**Comment by jasonharrison** [comment]
Hi, thanks for checking out FBG!  You are right, our blog is outdated. I will make sure it is updated-- sorry for that. 

I've encountered this error before but I don't recall what the problem was.  I will check my commit history/laptop later today and get back to you.

**Comment by Yannick-S** [comment]
I also suggest that the property gameArgs is not optional, if it leads to a runntime crash.

**Comment by jasonharrison** [comment]
Hi again!  I'm glad you got it working, and sorry for the trouble.

> Can you confirm for me that this is indeed the intended fix? I would then go ahead and update the Blog.

I've run into this error before and I don't quite remember what the problem was, but it sounds like your fix could be right. 

> I also suggest that the property gameArgs is not optional, if it leads to a runntime crash

Agree entirely!  

So I want to do some research to be sure this is the "correct" fix, but go ahead and create your pull requests  :) I will edit them if needed.

**Comment by flamecoals** [comment]
Your fix is correct, thank you for your help!
