### ISSUE TITLE
Problems with Secret Codes

### ISSUE THREAD

**Issue by gk-patel** [freeboardgames/FreeBoardGames.org#504]
Hi Guys, 

I have tried again with 4 people and I see no difference. I have see the following problems, 

1. I am able to select more than one Spy Masters (and there is no possibility to deselect when that happens). When PLAY is pressed, the game crashes. 
![image](https://user-images.githubusercontent.com/42677721/79244418-2d091780-7e77-11ea-80ee-b8bb9c175031.png)

2. When player is taking TURN to select the card, i think he is allowed to select only one CARD. Once this card is selected, it is possible to click on another card and then the game breaks. 

3. Sometimes, even though just one SpyMaster is selected and everything is supposidely normal, I get the following, 
![image](https://user-images.githubusercontent.com/42677721/79244948-bcaec600-7e77-11ea-971b-787ea619597a.png)
(this is what I also get for the 2 points mentioned above) 

Thanks.

**Comment by Spooky-0** [comment]
For 2: We were able to select more than one  card in a single turn. We  selected two correct ones, and then a neutral one - after selecting neutral the game crashed.
