### ISSUE TITLE
[Infrastructure] Is there a leave button here

### ISSUE THREAD

**Issue by peacetrue** [freeboardgames/FreeBoardGames.org#549]
If my friend can't play games with me, I can leave(to choose game mode page) and choose to play with AI.

![image](https://user-images.githubusercontent.com/38878763/81512839-5756d380-9356-11ea-805d-5fe5334e348b.png)

**Comment by jasonharrison** [comment]
There is currently no way to leave a room in an online game. The workaround is to start a new game/room. 

We are currently working on a major overhaul to the lobby system, which should be ready soon.

**Comment by peacetrue** [comment]
@jasonharrison You mean current, Then it can be solved in the future. Looking forward to your major overhaul.

**Comment by jasonharrison** [comment]
Our plan for the new lobby system is players will be able to leave the room by simply closing their browser window. 

If you're curious, here is the pull request for our backend: https://github.com/freeboardgames/FreeBoardGames.org/pull/545 (still a work in progress)

Thank you for the feature requests!

**Comment by flamecoals** [comment]
I will leave it open so we dont forget

**Comment by jasonharrison** [comment]
@flamecoals good idea, I'm still getting used to this idea of using GitHub issues as a to-do list :p

**Comment by flamecoals** [comment]
we added the "leave room" button ~ a week ago :)
