### ISSUE TITLE
Error in tutorial

### ISSUE THREAD

**Issue by pau1ie** [freeboardgames/FreeBoardGames.org#581]
I followed [the tutorial](https://www.freeboardgames.org/blog/2019/06/17/Publishing-your-first-boardgame-io-game-in-FBG/) which is nice and easy to get working with one exception. It says to `import IGameCTX from 'boardgame.io/core'`
but it seems this should be 
`import Ctx from 'boardgame.io'` 
I think this should be in the board and game files. I am not familiar with the framework so can't be sure what the code should be, but the other examples seem fairly clear.

**Comment by flamecoals** [comment]
Yes, you are correct, sorry for the outdated tutorial. I already sent a PR to update this, and will be pushing to the blog soon.

Thanks for reporting this! And feel free to message us on Discord if you have questions!

**Comment by flamecoals** [comment]
@pau1ie I would recommend syncing to HEAD now, as we just pushed a refactor and there are more changes on the tutorial, here is a summary from discord:

![image](https://user-images.githubusercontent.com/1034631/83345690-186bcc00-a2cb-11ea-8ed7-2c3bce79a2d3.png)
