### ISSUE TITLE
[Secret Codes] display a Spy emoji in the player badge

### ISSUE THREAD

**Issue by mateusazis** [freeboardgames/FreeBoardGames.org#587]
It may be useful since #543 will make it less obvious who the Spy is: 🕵️

**Comment by flamecoals** [comment]
That's true :) probably want to extend the PlayerBadge component to allow such customization in a generic way :)

Check our storybook:
https://www.freeboardgames.org/docs/?path=/story/games-shared-components-badges-playerbadges--with-score
