### ISSUE TITLE
[Checkers] Bug with logic that determines valid moves for kings

### ISSUE THREAD

**Issue by eemp** [freeboardgames/FreeBoardGames.org#604]
It looks like there may be a bug with checkers logic determining valid moves for kings unless the following is intentional:

![image](https://user-images.githubusercontent.com/4442378/85212046-ce4f9680-b31c-11ea-874f-0f5944da5853.png)

**Comment by flamecoals** [comment]
Thanks for reporting this! I will have a look into the rules and see if this was intentional or not

**Comment by flamecoals** [comment]
@JosefKuchar was this intentional or not ?

As a kid I've played like this (jumping the whole diagonal), but I think the most common rule played in US just go one space backward.

**Comment by flamecoals** [comment]
FYI, I believe this might be a misunderstanding about checkers rules, as they vary by region.  I think we should change the rule to be based on the most common US/International played rules, which would make this move illegal. However, I also believe we need to open the possibility of rule variations within the game.

**Comment by flamecoals** [comment]
Checkers is our most played game right now, and we are showing up as the first positions in search engines for it. So I will raise this as high priority because it might be surprising/upsetting people.

**Comment by ProspectPyxis** [comment]
Closed by #971, there's now a configuration option to enable or disable "flying kings" - it's also off by default.

**Comment by vdfdev** [comment]
Great job @ProspectPyxis, thank you for fixing this long-standing issue!!!
