### ISSUE TITLE
Zoo Parade: Message appears for invalid hint.

### ISSUE THREAD

**Issue by DanielSherlock** [freeboardgames/FreeBoardGames.org#625]
If a player tries to give a hint when none are available, it seems the info-message appears with the previous info.

Ideally, I think no info-message should appear (or the hint icons themselves should be unclickable)...

Or the message that does appear should explain that giving a hint is invalid (and why).

**Comment by flamecoals** [comment]
I agree, that should be a simple fix if someone have time to get to it... I might eventually...

**Comment by flamecoals** [comment]
I played with some friends and I noticed this issue. We should hide the hint buttons if they are not possible

**Comment by ysaive** [comment]
This should be fixed with latest changes. [I only removed the bottons on the frontend]

**Comment by flamecoals** [comment]
Fixed
