### ISSUE TITLE
[Secret Dracula] Improve UI

### ISSUE THREAD

**Issue by gk-patel** [freeboardgames/FreeBoardGames.org#677]
Hi Guys, we have a very nice game Secret Dracula. Very humbully I would like to suggest that the UI needs some re-doing, 
I have made a small proposal/draft here,

![image](https://user-images.githubusercontent.com/42677721/99715499-3f030680-2aa7-11eb-952d-a3cd0132c375.png)

I think most of the points are self-explanatory. Except 3, here I suggest we adapt the width, so for 5 players, we have 3+2 (3 in first row, 2 in second row), for 7 we have 4+3, and for 10 we have 5+5 (i think you can interpolate in between) . In the boxes representing the players, we can put all our cool emojis and name of players and badges.

I think we should use SVGs for responsive design, but if you are good at something CSS-ish, that would be fine.

An alternative design for point 2 could be as follows, but I prefer the one on top.  
![image](https://user-images.githubusercontent.com/42677721/99716136-09aae880-2aa8-11eb-9ac3-845c92643324.png)

Thanks for time and consideration.

**Comment by flamecoals** [comment]
I agree we can improve the Secret Dracula UI a quite bit :). We could do it incrementally, i.e. starting replacing the board which seems to be the most confusing one using emojis. 
I would love to help, but I am prioritizing other tasks related to infra, before I can get to this... So whoever want to volunteer, this is a good issue that can be done incrementally :)

**Comment by flamecoals** [comment]
@Spooky-0 just sent a PR that improved the UI a lot. I think it is very accessible and easy to play now.

Creating a full blown graphical UI would be nice as long as it improves the UX if someone wants to volunteer... But the same can be said of many other games that we lack animation/polish in general.

**Comment by gk-patel** [comment]
I will give it a try.

**Comment by gk-patel** [comment]
The UI is finalized, but the game-code needs some brush up.

Mainly the following two points, 
1. for multiple players, the Dracular color/crown is not rendered properly, as incorrect draculaID is recieved from G. 
2. Dead people still need to participate in the vote !

**Comment by Spooky-0** [comment]
Frontend Issues:
1) When there are more than 5 players left alive/playing, then the last Mayor is not eligble to be voted as Priest. The frontend displays a ? on the last Mayor anyways. See Rules:
`ON ELIGIBILITY:•Term limits apply to the President and Chancellor who were last elected, not to the last pair nominated. 
If there are only five players left in the game,  only the last elected  Chancellor  is ineligible to be Chancellor Candidate; the last President may be nominated.`
