### ISSUE TITLE
An error occurred while loading the lobby. Try reloading.

### ISSUE THREAD

**Issue by DiabolicAngeL** [freeboardgames/FreeBoardGames.org#701]
Hello,

I installed using the info on main page

```
git clone https://github.com/freeboardgames/FreeBoardGames.org
cd FreeBoardGames.org

yarn install  # installs dependencies

yarn run dev  # runs the webserver and backend (for online multiplayer games)
```

but i get this error "An error occurred while loading the lobby. Try reloading." whenever opening the games page.
Also I'm getting "Unknown error" when trying to set a nickname. I'm a newbie, can you help me?

Thanks a lot!

**Comment by cwatsonc** [comment]
You might try the Discord channel where there's usually somebody around to answer questions.

**Comment by flamecoals** [comment]
Weird. Do you get any errors on the console? What about network tab? Are you in windows? Please take a look into this workaround if you are running in windows: https://github.com/freeboardgames/FreeBoardGames.org/issues/678

**Comment by flamecoals** [comment]
Discussed in discord. Had port 3001 in use so fbg-server wouldn't start and give these errors. It would be good if we had a way to allow users changing ports, but he was able to kill the other process running on that port . Closing now.
