### ISSUE TITLE
[Infrastructure] Implement a project code of conduct

### ISSUE THREAD

**Issue by kevindigo** [freeboardgames/FreeBoardGames.org#729]
I would suggest just adopting an existing standard, like the Contributor Covenant: https://www.contributor-covenant.org/

If that's something you want to move forward with, I would be happy to put up a PR.

**Comment by flamecoals** [comment]
Yes, I think that is a great idea. If you can put up a PR, it would be appreciated.

**Comment by kevindigo** [comment]
Cool. Things got busy here, but I'll try to put something up this weekend. If someone else does so before then, I won't be offended.

**Comment by kevindigo** [comment]
@flamecoals: Sorry about the delay. I was starting to work on this, and realized that the CoC requires contact information for someone to report problems to. Since GitHub doesn't have a direct message feature (unfortunately), it would either have to be an email address, or some other contact point. 

What would you like me to use?

**Comment by jasonharrison** [comment]
Hmm. I don't think we ever set up @fbg.org email, and free G Suite is super limited now.

Maybe there are alternative free email hosts?  Or Google domains might have email forwarding?  I'll check when I get home.

**Comment by flamecoals** [comment]
@jasonharrison let's setup a contact@freeboardgames.org being a simple DNS forward for a google group with the project admins. I can do that tomorrow

**Comment by vdfdev** [comment]
Done!
