### ISSUE TITLE
[Checkers] Visual feedback when only select pieces can be used

### ISSUE THREAD

**Issue by mateusazis** [freeboardgames/FreeBoardGames.org#734]
**Is your feature request related to a problem? Please describe.**
When it is mandatory to pick one from a set of moves, it would be nice to highlight those pieces to make it clear why other pieces are unresponsive.

**Describe the solution you'd like**
Maybe a red circle around the pieces that must be moved or similar.

**Describe alternatives you've considered**
Flashing red the unused pieces if you click them when.

**Additional context**
N/A

**Comment by flamecoals** [comment]
Agreed, this would be a nice improvement. And checkers is the most popular game we have

**Comment by mateusazis** [comment]
Fixed by #954.
