### ISSUE TITLE
Bulls and cows hints seem wrong.

### ISSUE THREAD

**Issue by Spooky-0** [freeboardgames/FreeBoardGames.org#737]
**Describe the bug**
It seems that the hints are generated double , see image. 

**To Reproduce**
1. Find a colour which is present on the board 
2. Guess this colour 4 times, it will give you correct/hints for all four.

**Expected behavior**
If a colour only exists once in the solution, I only expect to see one hint if I guess this colour twice.

**Screenshots**

![Screenshot_2020-12-30-11-21-09-881_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/20541107/103345289-ebfa7700-4a88-11eb-9d39-58adad1a9f1c.jpg)

**Comment by flamecoals** [comment]
@leocaseiro Hey Leo, could you take a look at this? how hard it is to fix?

**Comment by leocaseiro** [comment]
Sure, I'll look into that this week.

For the time being, the secret will never repeat a colour.

**Comment by leocaseiro** [comment]
PR at https://github.com/freeboardgames/FreeBoardGames.org/pull/751
