### ISSUE TITLE
Closing / Credits splash dialog on game end

### ISSUE THREAD

**Issue by sefgit** [freeboardgames/FreeBoardGames.org#747]
What is the recommended method to display a closing/credits-splash dialog on game end before jumping to final scoreboard page ?
It would be great for example on finishing game of memorymatch when players can have a short look on the final board and after a period of time and/or button click, the final scoreboard page will be displayed.

Thank you

**Comment by gk-patel** [comment]
This is very easy. We just need to pass the baord to the GameLayout at the end.
