### ISSUE TITLE
Checkers Double Jump Crashes Game

### ISSUE THREAD

**Issue by jackjbridge-socceranalytics** [freeboardgames/FreeBoardGames.org#750]
**Describe the bug**
In online multiplayer mode, the checkers game crashes every time a user faces a double jump scenario.

**To Reproduce**
1. Set up a multiplayer online checkers game
2. Set up a double jump scenario (spot where one user would have two continuous jumps
3. Perform the first jump

**Expected behavior**
The user should be able to make the double jump without the page crashing

**Desktop (please complete the following information):**
 - Mac OS
 - Chrome

**Comment by flamecoals** [comment]
Hi @jackjbridge-socceranalytics, thanks for reporting this issue! 

I tried one game with the double jump scenario and it worked for me. Can you please send a screenshot with the board configuration which this happens? It would help us a lot to reproduce the issue.

I am also wondering if it could be related to other UX-related issues that we will fix soon

**Comment by jackjbridge-socceranalytics** [comment]
![Double Jump Issue](https://user-images.githubusercontent.com/73715318/104866204-97b61a80-5903-11eb-9b26-a90059892535.gif)

Hi! No problem. Thanks for looking into it! I recreated here with this gif.

**Comment by leocaseiro** [comment]
I confirm I was able to replicate the exact same error. Any jump that needs to be done twice, BOOM!

**Comment by leocaseiro** [comment]
This is the error I'm getting:

> react_devtools_backend.js:2430 TypeError: n.sum is not a function


This is the broken function
`var f = n.sum(c.multiply(p));`

Which leads to https://github.com/freeboardgames/FreeBoardGames.org/blob/master/web/src/games/checkers/game.ts#L102


```js
function g(t, e, r, n) {
    var o, a = [], i = !1, s = l(r.isKing ? m : y[e]);
    try {
        for (s.s(); !(o = s.n()).done; )
            for (var c = o.value, u = null, p = 1; r.isKing || p < 3; p++) {
                var f = n.sum(c.multiply(p));
                if (!f.inBounds())
                    break;
                var h = t.board[f.toIndex()];
                if (null !== h && h.playerID === e)
                    break;
                if (null !== h && h.playerID !== e) {
                    if (u)
                        break;
                    u = f
                }
                if (null === h) {
                    if (a.push({
                        from: n,
                        to: f,
                        jumped: u
                    }),
                    u) {
                        i = !0;
                        break
                    }
                    if (!r.isKing)
                        break
                }
            }
    } catch (d) {
        s.e(d)
    } finally {
        s.f()
    }
    return {
        moves: a,
        jumped: i
    }
}
```


https://user-images.githubusercontent.com/940070/104919615-a4616e00-59ea-11eb-823f-d316b3431954.mp4

**Comment by leocaseiro** [comment]
Hi @mateusazis, for my quick investigation I'm suspecting of this PR https://github.com/freeboardgames/FreeBoardGames.org/commit/e0e6f2b4817f788e5a6507a82f070f270cf125ef

Would you mind testing that scenario, please?

Thanks

**Comment by mateusazis** [comment]
This seems to be caused because I'm passing an objects with methods to the game state, but the class is lost when it gets serialized back-and-forth between client and server. It does not seem to happen in local mode.

I am having some trouble reproducing this in tests, but converting (serialized data=>class) should fix it. Sending a PR.

**Comment by flamecoals** [comment]
Thanks @leocaseiro for debugging and @mateusazis for the quick fix, this is in prod now!
