### ISSUE TITLE
Bulls & cows gives wrong hints

### ISSUE THREAD

**Issue by thgh** [freeboardgames/FreeBoardGames.org#761]
**Describe the bug**
Sometimes there are 5 hints and sometimes the hints are wrong

**To Reproduce**
See image

**Expected behavior**
Same hinting as in Mastermind

**Screenshots**
Wrong hints: 01, 02, 06
![Screenshot 2021-02-19 at 13 45 46](https://user-images.githubusercontent.com/1109982/108506624-61c8d500-72b9-11eb-94a4-20bcc58eab88.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome

**Additional context**
It seems the moon symbol causes the wrong hints

**Comment by flamecoals** [comment]
Thanks for reporting this @thgh ! Do you know what could be happening, @leocaseiro ?

**Comment by vdfdev** [comment]
Yeah, the code changed the hing logic, I think this is fixed. Please reopen if it isn't the case

**Comment by thgh** [comment]
Thanks 😄  I tried it out and it works fine!
