### ISSUE TITLE
[Bug] Bombs and Bunnys  - Game enters state with no legal moves

### ISSUE THREAD

**Issue by Spooky-0** [freeboardgames/FreeBoardGames.org#763]
**Describe the bug**
I played Bombs and Bunnies a while back and we got into a state with no legal moves. I am sorry to say that I don't really remember the exact details.

**To Reproduce**
We played a six player game, and then the second player died (ran out of cards) there was no player with an active move. The game was stuck.

**Expected behavior**
That the game would continue

**Comment by flamecoals** [comment]
Thanks for reporting this @Spooky-0. @b-hub do you have any idea what might be? It would be great if we could reproduce the issue

**Comment by b-hub** [comment]
Not sure, but I will add some 6 player tests and see if anything turns up

**Comment by b-hub** [comment]
I think this issue can be closed now @flamecoals

**Comment by flamecoals** [comment]
Thank!
