### ISSUE TITLE
can't get multiplayer link loading

### ISSUE THREAD

**Issue by UnknownBeanSmol** [freeboardgames/FreeBoardGames.org#773]
**Describe the bug**
when i click any game, when i want to send a link to someone, it won't load, and ends with error.
**To Reproduce**
1. Go to freeboardgames.org
2. Click on checkers
3. Scroll down to share a link and play with a friend online and click play

**Expected behavior**
the play button should go gray and say loading for a few minutes and say error after too long
**Screenshots**
![image](https://user-images.githubusercontent.com/82841616/115294390-2a8e6d00-a11e-11eb-8e2d-22e9666ea8a9.png)
![image](https://user-images.githubusercontent.com/82841616/115294395-2cf0c700-a11e-11eb-8aaa-0067e6816cac.png)

**Desktop 
 - OS:  18363.1500
 - Browser  chrome
 - Version 89.0.4389.128

**Comment by vdfdev** [comment]
Thanks for reporting this @UnknownBeanSmol. We are having some issue with our `fbg-server` crashing and causing this. It should be fixed now but I will leave this bug open until I have a more definitive solution.

**Comment by vdfdev** [comment]
Issue happened again today, we were able to test and had a discussion on discord
