### ISSUE TITLE
Private/password protected rooms?

### ISSUE THREAD

**Issue by ProspectPyxis** [freeboardgames/FreeBoardGames.org#784]
Not sure if I'm missing something obvious on the site, but as of now, there seems to be no way to create private or password protected rooms. I tried to test creating a room to play with my friends later, but after choosing a game and a nickname, it jumped me straight into a lobby with basically no options to change anything other than the game. I tried to leave the room and recreate it, and my game was just listed there out in the open for anyone to join for a while.

A cursory search through both the issues and the projects page here didn't bring up anything related to this, either. I'm wondering if this is intentional - if so, is there a reason private rooms won't be implemented, or if not, are there any plans to implement them in the future?

**Comment by ProspectPyxis** [comment]
Partially disregard - you create private rooms by clicking on the game list down below. It was a bit confusing at first though that the clearly visible "new room" button can only create a public room...maybe that should be changed to be a bit clearer, but I'm just throwing ideas out at this point.

**Comment by vdfdev** [comment]
Hi, thanks for getting in touch with us! I agree that the public/private room could be a bit clearer, I will keep in mind about this confusion when we get to redo the public rooms functionality with ranking and so on.
