### ISSUE TITLE
[i18n] Display a warning when a game is not fully translated

### ISSUE THREAD

**Issue by richardaum** [freeboardgames/FreeBoardGames.org#803]
## Proposal

When a game is not fully translated, a warning should appear to request translators from the community.

![image](https://user-images.githubusercontent.com/2018161/117671967-be80b100-b17f-11eb-9d29-acfd19b00767.png)

Original request:

> Can we somehow not show the game if it is not translated on the home page for a given language? Or at least show an warning asking for contributions...

**Comment by richardaum** [comment]
@vdfdev is it better now?

**Comment by richardaum** [comment]
Preview from GameInfo:

![image](https://user-images.githubusercontent.com/2018161/117752061-83689700-b1ec-11eb-951c-b9976b39172c.png)

**Comment by vdfdev** [comment]
@richardaum This looks great! :D 

I would just change the english copy a bit:
"This game is not fully translated to your language yet. Click here to learn how to help us translating it."
@jasonharrison wdyt?
