### ISSUE TITLE
Fbg-server high latency on 14-people game

### ISSUE THREAD

**Issue by vdfdev** [freeboardgames/FreeBoardGames.org#806]
**Describe the bug**
I was playing secret codes with my coworkers today, and everything related to fbg-server was suuuuper slow. Chat messages were taking around 5s to appear after sending, and the initial "loading" took so long that I thought it was broken. I am not sure why this is happening though.

**To Reproduce**
1. Create game with 14 ppl 
2. Send a chat message
3. Wait 5s to receive it back

**Expected behavior**
Less than 1s latency

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome

**Comment by vdfdev** [comment]
By the way, I tried to reproduce this in a room with just me, and it was super quick. Not sure if the pub/sub is blocking until everything is delivered or something...

**Comment by vdfdev** [comment]
This happened to me again today with a 2 ppl match only, with a stranger online. I am not sure what is going on, my best hypothesis right now is that someone with a slow connection might be slowing things down? But that kinda doesn't make sense. I will try to reproduce this with a device in a slow connection

**Comment by cwatsonc** [comment]
not sure what granularity you have on monitoring but not sure that high
latency describes this (my understanding of arch is modest) -- even if
you're passing full state of game each state change -- does the latency
occur for both players (symmetrical)? One concern is if they are disparate
regions (e.g. Asia - N America) ws here the network distance calculations
can get extreme. You guys did a lot of i18n work recently. Is that
impacting the server r/t somehow?

**Comment by vdfdev** [comment]
@cwatsonc the latency I experienced were not related to game moves, they were mainly related to chat. I don't believe the i18n work has anything to do with it, given that it is mainly limited to the frontend code. I am improving our monitoring game so we can have some metrics, and I found out that our servers were being throttled, so that might be related.

**Comment by vdfdev** [comment]
Ok, I think I figured it out. Our database is not fitting anymore on one of our nodes:

![image](https://user-images.githubusercontent.com/1034631/127753347-7f500c89-fa65-44a7-9f0c-9b1a70c3c3cb.png)

A load of 6 for 15 mins means that in 15 mins we had 6 times the amount of work to be done vs capacity... Even though k8s was smart enough to only provision the database pod to this node, during peak times it is getting overloaded. The chat message pings the database for authentication, and this would explain the (seemly random) delays.

I will 1) try to see if we can optimize some queries to reduce load and 2) see what I can afford in terms of giving more CPU to the database.

**Comment by vdfdev** [comment]
I believe this should be fixed now, I moved from 3 machines with 2 CPUs each to 2 machines with 4 CPUs each. I've also added alerts to the load so we can spot this before it gets so bad. I also found that we were doing full table scans for the lobby, which might explain the slow down on fbg-server.
