### ISSUE TITLE
[Nine Men's Morris] Local Version Sometimes Has White Background

### ISSUE THREAD

**Issue by Kurt-von-Laven** [freeboardgames/FreeBoardGames.org#902]
**Describe the bug**
Sometimes the local version of the game has a white background. This is problematic, because the instructions are in white font, and half of the pieces are white. I do not know whether this bug affects the online version.

**To Reproduce**
1. Go to [Nine Men's Morris on web](https://www.freeboardgames.org/en/play/ninemensmorris).
2. Play a local game.
3. Sometimes the background is white instead of black. The black background may or may not appear briefly first.

**Expected behavior**
I expected the background to be black consistently.

**Screenshots**
![White Background](https://user-images.githubusercontent.com/974910/120133551-3e97a680-c181-11eb-9415-0713e09fbdfc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser: Google Chrome 91.0.4472.77

**Additional context**
I use an external monitor and Ubuntu's built-in night light feature to reduce blue light.

**Comment by vdfdev** [comment]
This line should probably not be in the constructor of the react component:
https://github.com/freeboardgames/FreeBoardGames.org/blob/b596fda05f77b5ac208e842769fcd25f6d40f665/web/src/gamesShared/components/fbg/GameDarkSublayout.tsx#L43

I think newer versions of react have other lifecycle methods that would always execute when the component is displayed.

**Comment by jasonharrison** [comment]
> I think newer versions of react have other lifecycle methods that would always execute when the component is displayed.

`componentDidMount()` ? https://reactjs.org/docs/react-component.html#componentdidmount

😄
