### ISSUE TITLE
After playing a game, FBG stays with a black background.

### ISSUE THREAD

**Issue by Spooky-0** [freeboardgames/FreeBoardGames.org#914]
**Describe the bug**
When going to FBG homepage, the background is white and text is black. Most games have a black background. After playing a game you see the end-game screen (see screenshot). Using the links to navigate through FBG, the background remains black. This means you can't read any text. Refreshing the website helps.

**To Reproduce**
1. Play game (e.g. Bulls and Cows)
2. Finish a game. Background remains black.
3. Navigate FBG without refreshing the page. (aka use Single Page Application magic, not browser back/forward refresh.)

**Expected behavior**
Background should return to white. Then, everything would be legible.

**Screenshots**!
[image](https://user-images.githubusercontent.com/20541107/125260693-e1a31a80-e300-11eb-86e4-187a799a74fc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox

Sadly I can't fix this, because CSS is black magic to me.

**Comment by vdfdev** [comment]
Thanks for reporting this @Spooky-0, I thought I had fixed that ... I will try to reproduce this issue again

**Comment by vdfdev** [comment]
weird. I could reproduce this now using the local mode only. I will look into it now that it is very reproducible
