### ISSUE TITLE
Add https://www.freeboardgames.org/*/room/* to robots.txt

### ISSUE THREAD

**Issue by jasonharrison** [freeboardgames/FreeBoardGames.org#916]
**Describe the bug**
We should add https://www.freeboardgames.org/*/room/* to robots.txt (or otherwise block search indexing) to improve SEO

**Note last result:** 
![Screenshot_20210719-001607](https://user-images.githubusercontent.com/304383/126102217-3232b3a0-dece-4d78-bf66-eb7667ce1e3b.png)

**Comment by vdfdev** [comment]
Added to #915
