### ISSUE TITLE
Run on own server

### ISSUE THREAD

**Issue by tuxor1337** [freeboardgames/FreeBoardGames.org#918]
Hey, I would like to run this on my own server to test a game I implemented with friends. Unfortunately, I don't have docker or kubernetes, but only a shared web host from https://uberspace.de

On my web host, I was able to run the dev server with `yarn run dev`. The service listening on `0.0.0.0:3000` is then redirected to my public domain via this procedure: https://manual.uberspace.de/web-backends/ However, games don't work, because the other services (on ports 3001 and 8001) are not exposed. I get the following error:

```
[HPM] Error occurred while trying to proxy request /graphql from [MY_PUBLIC_DOMAIN] to http://localhost:3001 (ECONNREFUSED)
```

How would I configure my own server for testing without Docker or Kubernetes? Do ports 3001 and 8001 need to be accessible from outside? By the way, I also noticed with `netstat -tunlp` that nothing seems to be listening on `0.0.0.0:3001` but only on `:3000` and `:8001` - maybe a process was killed here? I find this quite hard to debug.

It might as well be a memory issue - is there any quick fix to reduce memory use of the server?

**Comment by vdfdev** [comment]
Added https://www.freeboardgames.org/docs/?path=/story/documentation-deploying-running-with-nginx--page
