### ISSUE TITLE
Size and placement of GameDarkSublayout

### ISSUE THREAD

**Issue by tuxor1337** [freeboardgames/FreeBoardGames.org#922]
I have two issues with the `GameDarkSublayout` sizing and positioning properties:

1. Why is there a strict maximum of 1000px in width? Many games could profit from using more space. It doesn't necessarily mean cramming more stuff into the area, but it could mean increasing the size of fonts or assets, or the spacing between elements for a less-crammed look-and-feel. And not only desktops, but even smartphones might exceed the 1000px when in landscape mode so that they see unnecessary black bars. I think this should be adjustable somehow by the user of that Component. 
2. Currently, the vertical positioning might look nice and centered on large screens, but it will produce unnecessary empty (black) space below the game board, when the screen height is low. Furthermore, when the screen height decreases, the game board moves to the top, out of the viewport, so that the user can still acess things at the bottom by scrolling down, but can't reach the top parts of the board. See this video:

https://user-images.githubusercontent.com/1518387/128779445-15964878-cfbe-4eb5-8230-bdfb0d09e7d7.mp4

My suggestion for the first point would be to either add a new property or to replace the boolean `allowWiderScreen` property by a string property that directly sets `maxWidth` and defaults to `"500px"`. 

For the second point I would actually prefer to give up the vertical centering on large screens, and simply have the board position at the upper edge. The following lines would be modified ...:
https://github.com/freeboardgames/FreeBoardGames.org/blob/269dae953bfc5488ea899c051623956d58be25be/web/src/gamesShared/components/fbg/GameDarkSublayout.tsx#L107-L113
... like this:
```
            position: 'relative',
            width: '100%',
            maxWidth: this.props.maxWidth || '500px',
            color: 'white',
            margin: '0 auto',
```

If you insist on the vertical centering, then you should do this in a way that doesn't let the board move out of the viewport so that stuff can't be reached, even when scrolling. My proposal for that would be to replace the above CSS properties as follows...:
```
	position: 'relative',
	width: '100%',
	maxWidth: this.props.maxWidth || '500px',
	color: 'white',
	display: 'inline-block',
	verticalAlign: 'middle',
	lineHeight: 'normal',
```
... and then wrap that `div` into another `div` with the following properties:
```
	position: 'relative',
	width: '100%',
	height: 'calc(100vh - 49px)',
	textAlign: 'center',
	lineHeight: 'calc(100vh - 49px)',
```
I have only tested this in Firefox for desktop though.

**Comment by vdfdev** [comment]
@tuxor1337 Hey, I am happy to accept your suggestions. My only concern is that we have several games relying on the vertical centering right now, so maybe we can disable it only when some parameter is set ? Same thing for the "allowWiderScreen", even though I think it would be easier to just replace it in all the games with the equivalent code (i.e. 500px width string)

Happy to accept PRs to increase the flexibility of this layout :)

**Comment by tuxor1337** [comment]
Okay, I will be happy to prepare a PR. But first, can you name one or more games that currently rely on the vertical centering so that I can see in which way they rely on it?

**Comment by tuxor1337** [comment]
Okay, I just checked all the games manually. Here is my PR, I only had to adjust the Zoo Parade a little bit:  #923

**Comment by vdfdev** [comment]
Thank you 😊 ! I should deploy your changes tonight

**Comment by vdfdev** [comment]
Done, worked like a charm! Deployed to prod :) Thanks @tuxor1337 !
