### ISSUE TITLE
[Checkers] Possible game improvements/new game options

### ISSUE THREAD

**Issue by ProspectPyxis** [freeboardgames/FreeBoardGames.org#946]
**Is your feature request related to a problem? Please describe.**
I played a game of checkers with a friend, and I noticed quite a few flaws that make the game not as smooth as it could be. Plus, I also had some thoughts about possibly adding new configuration options to the game.

**Describe the solution you'd like**
I'd like to see the following features implemented in the game:
- A configuration option to enable or disable forced capture.
- Better indication for invalid moves when there is a forced capture on the board - for example, a red flash on the piece you're trying to move.
- A configuration option for whether kings can move any amount of squares or only one square per turn. 
- Might be a bigger scope than the other two configuration options, but an option to set the amount of pieces each player has between 8 (2 rows of pieces) and 12 (3 rows).

The rationale behind the configuration options is that checkers seems to be one of those games where everyone plays it differently in some way, and it can be quite jarring to be forced into one standard ruleset - my friend was very surprised about kings going any distance diagonally, while I was surprised that the game uses three rows of pieces per player instead of two.

As for the request for making invalid moves with forced capture more clear, the rationale is that it can be very jarring to have moves simply quietly fail with no indication, as I've run into the problem of not seeing the forced capture and being perplexed that my move just seems to not register at all a few times. I'm not sure how viable this is code-wise, though.

**Comment by vdfdev** [comment]
I completely agree, and this is something that would add a lot of value to FBG because it is our most played game! I will mark this bug as high priority and a good first issue (it isn't too hard)

**Comment by ProspectPyxis** [comment]
Going to list #604 as a related issue - it seems my friend isn't alone in being confused at the king's movement.

**Comment by vdfdev** [comment]
This PR https://github.com/freeboardgames/FreeBoardGames.org/pull/954  will happy alleviate some of those issues! Thanks @mateusazis for the great contribution!

**Comment by ProspectPyxis** [comment]
Every point I've brought up in this issue (and then some!) should be closed by #971!
