### ISSUE TITLE
Replace enum types by union types

### ISSUE THREAD

**Issue by tuxor1337** [freeboardgames/FreeBoardGames.org#998]
**Is your feature request related to a problem? Please describe.**
enum types are quite verbose and often complicate the code or produce redundant patterns. There are good reasons why TypeScript's union types are actually preferable to enum types: https://stackoverflow.com/questions/40275832/typescript-has-unions-so-are-enums-redundant (please read this, this stackoverflow request really is at the heart of my request)

**Describe the solution you'd like**
I would suggest to have all enum types in FBG's source code replaced by union types (with string literals). If you agree, this can be achieved with simple search-and-replace throughout the whole code base.

Alternatively, we should at least enforce all enum types to be string enums to avoid problems like this:
```
enum ZeroOrOne {
  Zero = 0,
  One = 1
}
const zeroOrOne: ZeroOrOne = 2; // no error!!
```
or this:
```
enum ZeroOrOne {
  Zero = 0,
  One = 1
}
interface SomeInterface {
  someAttribute?: ZeroOrOne;
}
function foo(val: SomeInterface) {
  if (!val.someAttribute) {
    // this will apply if val.someAttribute == 0, even though
    // the developer might actually want to test
    // `val.someAttribute === null || val.someAttribute === undefined`
    //  -> can be avoided with string enums or union types
  }
}
```

**Comment by cwatsonc** [comment]
Can unions serve the identical role in switch constructs?  I think they can, but just to confirm?

**Comment by tuxor1337** [comment]
> Can unions serve the identical role in switch constructs? I think they can, but just to confirm?

Yes, absolutely.

**Comment by richardaum** [comment]
Is there some piece of code in our repository that made you to suggest this change? Maybe if we look at that, we could get more motivated to apply that change and see how that improves the code, considering the use cases we have.

**Comment by tuxor1337** [comment]
I noticed that the use of enums is quite "unnatural" and comes with quite some redundancy, when I saw the `Phases` (and `Stages`) enums which are present in most games in FBG:
https://github.com/freeboardgames/FreeBoardGames.org/blob/c0ac2c50b3f97c6bb3309ddff58806203361e770/web/src/games/bombsAndBunnies/engine/interfaces.ts#L1-L8
With union types, this would be
```
const phases = ['initial_placement', 'place_or_bet', 'bet', 'reveal', 'penalty', 'result'] as const;
type Phases = typeof phases[number];
```
And you use the type like this:
```
let somePhase: Phases = "place_or_bet";
somePhase = "nonexistent_phase";  // throws error
```
However, there is a disadvantage of union types: They won't be implicitly typed in many cases. Example:
```
let somePhase = "place_or_bet";
somePhase = "nonexistent_phase";  // no error, of course
```
Most other non-trivial uses of enums are in the card games I recently added to FBG. There, I found that it's quite verbose to use the enums. Here are three examples in current implementation and, more concisely, with union types instead of enums:
https://github.com/freeboardgames/FreeBoardGames.org/blob/360bcb7eb210568f06ae21bc08e7ec49e8a66af0/web/src/games/zwanzigerrufen/util/misc.ts#L13-L15
```
export function suitRank(suit: Suit): number {
  return ["Diamonds", "Spades", "Hearts", "Clubs", "Trumps", "Excuse"].indexOf(suit);
}
```
https://github.com/freeboardgames/FreeBoardGames.org/blob/360bcb7eb210568f06ae21bc08e7ec49e8a66af0/web/src/games/zwanzigerrufen/util/misc.ts#L21-L23
```
export function getBidName(bid: Contract): string {
  return `bid_${bid.toLowerCase()}`;
}
```
https://github.com/freeboardgames/FreeBoardGames.org/blob/360bcb7eb210568f06ae21bc08e7ec49e8a66af0/web/src/games/zwanzigerrufen/util/misc.ts#L37-L53
```
export function allowedBids(players: IPlayer[], playerId: string): Contract[] {
  const player = players.find((P) => P.id == playerId);
  if (player.bid == "Pass") return [];
  const highestBid: Contract = Math.max(...players.map((P) => P.bid));
  if (highestBid == "Solo") return [];
  if (highestBid == "SoloSuit") return ["Pass", "Solo"];
  const result = ["Solo"];
  if (player.hand.filter((C) => !isTrump(C)).length >= 5) {
    result.unshift("SoloSuit");
  }
  if (highestBid == "Normal") {
    result.unshift("Pass");
  } else if (getCallCard(player.hand) !== null) {
    result.unshift("Normal");
  }
  return result;
}
```
Further reading: https://fettblog.eu/tidy-typescript-avoid-enums/

**Comment by richardaum** [comment]
Thank you for bringing up some examples to illustrate your proposal!

Just to be on the same page, what do you mean by "unnatural"?

**Comment by richardaum** [comment]
I aggre with the benefits of getting rid of those enums - we need to be sure that Typescript will notify us about wrong value assingments, and that doesn't happen when using enums (as is in the first example you provided).

> I would suggest to have all enum types in FBG's source code replaced by union types (with string literals). If you agree, this can be achieved with simple search-and-replace throughout the whole code base.

But I think it is not simples and also cannot be solve by search-and-replace approach. Let me explain why, picking  one of the snippets you sent:

```ts
export function allowedBids(players: IPlayer[], playerId: string): Contract[] {
  const player = players.find((P) => P.id == playerId);
  if (player.bid == "Pass") return [];
  const highestBid: Contract = Math.max(...players.map((P) => P.bid));
  if (highestBid == "Solo") return [];
  if (highestBid == "SoloSuit") return ["Pass", "Solo"];
  const result = ["Solo"];
  if (player.hand.filter((C) => !isTrump(C)).length >= 5) {
    result.unshift("SoloSuit");
  }
  if (highestBid == "Normal") {
    result.unshift("Pass");
  } else if (getCallCard(player.hand) !== null) {
    result.unshift("Normal");
  }
  return result;
}
```

In some cases, the enum is a good way to represent a specific logic. On this snippet, I understand that your suggestion is to replace `Contract` enum for a union type, right? Maybe something like this:

```ts
type Contract = 'None' | 'Pass' | 'Normal' | 'SoloSuit' | 'Solo';
```
But it isn't possible because later the following code appears:

```js
G.players.forEach((P) => {
  if (P.bid > G.contract) {
    // ...
  }
  // ... 
});
```

Notice how you compare the underlying numbers assigned to the enum. It is perfectly possible to refactor that code, BUT considering your proposal seems to lead to a broad refactory, it could take some time - which means that it not that simple. Are we considering that effort it requires?

**Comment by tuxor1337** [comment]
It's true that you can't blindly replace all enum types by union types without knowing the actual code. For the example that you gave, we don't need to worry, because I'm the author of those card games and since it's been only a few weeks since I wrote that code, I have perfect knowledge of everything I did there. If I'm doing the refactoring for the card games, I will definitely have a good overview and wouldn't miss that kind of aspect.

In my original post, I suggested to replace *all* enum types in FBG by union types. However, that was exaggerated. It is probably a bad idea to immediately replace all enum types everywhere in the code. For me, FBG is the first project in TypeScript where I actively contribute code. I have the impression that there is an unspoken policy to use enum types wherever there are constants flying around. But maybe I overinterpreted this. I would be happy if we said: Our policy is to use *either* enum *or* union types when there are (numeric) constants around.

Now for the word "unnatural": I have put the word in quotes because I'm not sure myself what I mean by it. A line like `initial_placement = 'initial_placement'` is unintuitive and artificial to me, or "unnatural". Maybe it also seems unfamiliar to me because I know the concept of enums from C and there you never write a line like `initial_placement = 'initial_placement'`, and you don't write `Phases.initial_placement`, but just `initial_placement`.

**Comment by vdfdev** [comment]
I think our policy is to use _strong types_ whenever it is possible, so the compiler can help us find bugs where possible. A good amount of game devs have been using strings or numbers directly (without typing) for storing constants, and I have always suggested to use enums. I was not aware about these trade-offs between enums and union types, but in my opinion both of those are great options compared to untyped strings or numbers. 

I don't see enough reason to outright ban enum types, or to bother replacing it by union types everywhere in our code.

This is a great discussion though that can inform next games being developed

**Comment by richardaum** [comment]
As we got on a common understanding that we can use both enum and union types, I'm closing this issue. Okay? Feel free to open it again if you feel we can go on another direction.
